services:
  - type: web
    name: blockmusic-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server-simple.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: WEB3_STORAGE_TOKEN
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDVENjk4MzQzRjg0NjQxMzE5MjQwNjQ2NjQxNjQ2NTY0NjQ2NTY0NjQiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2MzAwMDAwMDAwMDAsIm5hbWUiOiJCbG9ja011c2ljIn0.fake
